version: '3'
services:
  my-app:
    image: demifire/express-gallery:${IMAGE_VERSION}-local
    depends_on: 
      - db
      # this creates a dependency tree
    command: ["./node_modules/.bin/nodemon", "app.js", "npm", "run", "dev"]
    container_name: expressGallery
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
    networks:
      - my-app-network
  db: 
    image: postgres:10.0-alpine
    env_file: .env
    volumes: 
      - pg-data-volume:/var/lib/postgresl/data
    ports: 
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    networks:
      - my-app-network

volumes: 
  pg-data-volume:
networks:
  my-app-network: